"""Frozen experiment catalog for the 2026 MatterGen exploration archive.

The catalog intentionally stores scientific interpretation separately from the
source artifacts.  Historical verdicts remain untouched at their original
paths; ``result`` records the archive-level interpretation after all later
confirmatory work.
"""

from __future__ import annotations


ALLOWED_CATEGORIES = {"FULL_ARCHIVE", "SUMMARY_ONLY", "EXTERNAL_DATA_ONLY", "IGNORE"}
ALLOWED_STATUSES = {
    "SUPPORTED",
    "MIXED",
    "NOT_SUPPORTED",
    "FAIL",
    "INCONCLUSIVE",
    "ENGINEERING_ONLY",
    "ABANDONED_BEFORE_EVALUATION",
}


def rec(
    experiment_id: str,
    name: str,
    lineage: str,
    source_worktree: str,
    source_branch: str,
    source_commit: str,
    source_path: str,
    category: str,
    status: str,
    target: str,
    question: str,
    hypothesis: str,
    change: str,
    evidence: str,
    result: str,
    stopped: str,
    next_direction: str,
    used: str = "no",
    covered: str = "no",
    reproducibility: str = "PARTIAL",
    notes: str = "",
) -> dict[str, str]:
    return {
        "experiment_id": experiment_id,
        "experiment_name": name,
        "lineage": lineage,
        "source_worktree": source_worktree,
        "source_branch": source_branch,
        "source_commit": source_commit,
        "source_path": source_path,
        "category": category,
        "status": status,
        "archive_target": target,
        "scientific_question": question,
        "hypothesis": hypothesis,
        "change": change,
        "evidence": evidence,
        "main_result": result,
        "why_stopped": stopped,
        "next_direction": next_direction,
        "used_in_thesis": used,
        "covered_by_final_release": covered,
        "reproducibility_level": reproducibility,
        "notes": notes,
    }


MAIN = "/mnt/datasets-livsyn/dxl/mattergen_v1"
FINAL = "/mnt/datasets-livsyn/dxl/mattergen_v1_thesis_final"
BASE = "1af301c5e534ff6b9b9f96ea5dab48036d9c46af"
FINAL_COMMIT = "5b572c61c70c4287147616beae7f72d28955cf98"


EXPERIMENTS = [
    # Innovation 1: the order is the research timeline, not a ranking.
    rec("I1-00", "Fixed CFG baseline", "innovation1", FINAL, "release/thesis-final-2026", FINAL_COMMIT, "thesis_release/innovation1", "SUMMARY_ONLY", "SUPPORTED", "research_archive/innovation1/fixed_cfg", "What fixed-compute reference should all adaptive CFG variants use?", "A fixed CFG/reference policy provides an auditable matched-compute control.", "Established the non-adaptive reference arm.", "Frozen release manifests and paired controls.", "The fixed reference remained the required baseline throughout the lineage.", "Baseline role was complete.", "Compare every adaptive or branching policy against the same reference.", "core", "yes/core", "FULL"),
    rec("I1-01", "Adaptive CFG V1", "innovation1", MAIN, "archive/thesis-analysis-package-v1", "a367f85efe8027bf8ef2db41cc48ec2fd3d60582", "experiments/final_innovation1_audit", "FULL_ARCHIVE", "MIXED", "research_archive/innovation1/adaptive_cfg_v1", "Can online multi-field residual adaptation improve conditional generation?", "Residual-driven CFG updates will improve property error without harming structure quality.", "Introduced the original adaptive multi-field CFG controller and EMA/clipping choices.", "Original Formal256 evidence plus a later eight-seed minimal ablation audit.", "Historical positive evidence was not stable across the later batch; benefits and quality trade-offs coexist.", "Cross-batch inconsistency prevented a general stability claim.", "Audit harmful adaptation and preserve a reference branch.", "supporting", "yes/summary", "PARTIAL", "Historical conclusion and later thesis interpretation are deliberately separated."),
    rec("I1-02", "Robust Adaptive CFG V2", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_robust_adaptive_cfg", "experiment/robust-adaptive-cfg-v2", BASE, "experiments/robust_adaptive_cfg_v2", "FULL_ARCHIVE", "FAIL", "research_archive/innovation1/robust_v2", "Can calibrated residual normalization reduce V1 harmful adaptation?", "Timestep normalization, robust aggregation, slew limiting and fallback will make V1 reproducibly safer.", "Added deterministic replay calibration and bounded robust adaptive control.", "Calibration, fresh P0, paired statistics and harm/tail analysis.", "Fresh P0 failed the preregistered gate; Formal256 was correctly not run.", "The frozen P0 rule failed and rescue tuning was forbidden.", "Test whether oracle headroom exists before learning another controller.", "supporting", "yes/key-negative", "PARTIAL"),
    rec("I1-03", "Counterfactual Oracle V3", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_cfg_oracle", "experiment/counterfactual-adaptive-cfg-v3", BASE, "experiments/counterfactual_adaptive_cfg_v3", "FULL_ARCHIVE", "MIXED", "research_archive/innovation1/oracle_v3", "Does per-sample counterfactual selection reveal usable adaptive-CFG headroom?", "If harmful V1 decisions are avoidable, an oracle should expose a consistent selection advantage.", "Evaluated counterfactual candidates instead of committing to one online controller.", "Oracle audit, candidate metrics and paired counterfactual outcomes.", "The original oracle promotion gate failed, while later analysis retained evidence of avoidable harmful decisions.", "No deployable predictor followed from the oracle evidence.", "Calibrate risk and safe-selection rules, then move toward branching.", "supporting", "yes/key-negative", "PARTIAL"),
    rec("I1-04", "Risk-Calibrated CFG V4", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_risk_cfg", "experiment/risk-calibrated-adaptive-cfg", "a4fda8a573ee0e372d3b53064e235ae87f0e670c", "experiments/risk_calibrated_adaptive_cfg", "FULL_ARCHIVE", "FAIL", "research_archive/innovation1/risk_v4", "Can a risk model selectively suppress harmful adaptive decisions?", "Calibrated selective prediction will retain useful adaptations while rejecting risky ones.", "Added a frozen risk score and selective gate.", "Development calibration, selective gate metrics, decisions and seed-level tables.", "The selective gate failed; no fresh P0 or Formal256 was permitted.", "The preregistered calibration gate did not pass.", "Try explicit safe selection without changing the evaluated gate post hoc.", "supporting", "yes/key-negative", "PARTIAL"),
    rec("I1-05", "Safe-Selection CFG V5", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_safe_cfg", "experiment/calibrated-safe-selection-cfg", "7c9d9261d5064a37b8c4cd03a0ecf022621145a7", "experiments/calibrated_safe_selection_cfg", "FULL_ARCHIVE", "FAIL", "research_archive/innovation1/safe_v5", "Can conservative candidate selection deliver safe adaptive gains?", "A calibrated selection rule can avoid harmful candidates without discarding all gains.", "Replaced continuous adaptation with frozen safe candidate selection.", "Validation gate, calibration reports and stop decision.", "The validation gate failed; downstream P0/Formal stages were not run.", "The frozen validation rule rejected the policy.", "Investigate whether effects are stage- or field-specific.", "supporting", "yes/key-negative", "PARTIAL"),
    rec("I1-06", "Stage-Calibrated CFG", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_stage_cfg", "experiment/stage-calibrated-bounded-cfg", "f281462d8f690493f3bc3b78faffaea6abdeb2ae", "experiments/stage_calibrated_bounded_cfg", "FULL_ARCHIVE", "MIXED", "research_archive/innovation1/stage_cfg", "Are useful CFG adaptations concentrated in particular denoising stages?", "A bounded stage pulse will retain benefits while reducing broad harmful adaptation.", "Added frozen stage gating and bounded pulses.", "Calibration passed; a fresh P0 and paired endpoint analysis were completed.", "Pulse activity was measurable, but P0 failed and the stage-specific benefit was not supported.", "Fresh P0 failed under the preregistered rule.", "Test field-specific heterogeneity and simpler branch choices.", "supporting", "yes/key-negative", "PARTIAL"),
    rec("I1-07", "Field-Decoupled CFG", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_field_cfg", "experiment/field-decoupled-adaptive-cfg", "fca6b8d90e869c8c9535d7e5910e606efd722fdf", "experiments/field_decoupled_adaptive_cfg", "FULL_ARCHIVE", "FAIL", "research_archive/innovation1/field_cfg", "Can position, cell and atom fields be adapted independently?", "Field-decoupled decisions will exploit heterogeneous residual reliability.", "Separated field controllers with a frozen calibration protocol.", "Forty-eight calibration cases, eligibility tests and field-effect analysis.", "No eligible policy survived calibration; P0 and Formal256 were not run.", "The heterogeneity/calibration gate failed.", "Run zero-training diagnostics before any further field controller.", "supporting", "yes/key-negative", "PARTIAL"),
    rec("I1-08", "Adaptive Neighborhood P0", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_adaptive_neighbor", "experiment/adaptive-neighborhood-p0", BASE, "experiments/adaptive_neighborhood_p0", "SUMMARY_ONLY", "FAIL", "research_archive/innovation1/adaptive_neighborhood", "Can local neighborhood signals gate adaptation more reliably?", "Local structural context will identify beneficial adaptive events.", "Added neighborhood-derived decisions.", "Small P0, property/quality summaries and guardrails.", "P0 and its guardrails failed.", "No quality/property GO signal justified expansion.", "Prefer mechanisms with demonstrable branch-level headroom.", "no", "no", "SUMMARY_ONLY"),
    rec("I1-09", "Field Async Freeze", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_async_freeze", "experiment/field-async-freeze-p0", BASE, "experiments/field_async_freeze_p0", "SUMMARY_ONLY", "ABANDONED_BEFORE_EVALUATION", "research_archive/innovation1/field_async_freeze", "Can converged fields be frozen asynchronously?", "Fields converge at sufficiently different times to save or reallocate compute.", "Proposed per-field freeze schedules.", "Pre-generation heterogeneity diagnostic.", "The diagnostic gate failed; generation was not started.", "Required field heterogeneity was absent.", "Stop the asynchronous field family.", "no", "no", "SUMMARY_ONLY"),
    rec("I1-10", "Shared Field Dynamics Diagnostic", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_async_freeze", "experiment/field-async-freeze-p0", BASE, "experiments/shared_field_dynamics", "SUMMARY_ONLY", "INCONCLUSIVE", "research_archive/innovation1/shared_field_dynamics", "Do fields exhibit separable convergence dynamics?", "Observable field dynamics can justify asynchronous control.", "Measured field trajectories without committing to a new sampler.", "Saved diagnostic summaries and trajectories.", "Dynamics did not establish actionable heterogeneous control.", "Diagnostic evidence was insufficient for intervention.", "Use branch-level alternatives rather than per-field schedules.", "no", "no", "SUMMARY_ONLY"),
    rec("I1-11", "Site-Level Convergence Diagnostic", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_async_freeze", "experiment/field-async-freeze-p0", BASE, "experiments/site_level_convergence_diagnostic", "SUMMARY_ONLY", "FAIL", "research_archive/innovation1/site_convergence", "Can individual sites be declared converged early?", "Site-level residual heterogeneity is strong enough for safe freezing.", "Added site-level convergence probes.", "Diagnostic cohort and heterogeneity gate.", "The diagnostic failed; no safe intervention followed.", "Required heterogeneity was not present.", "Stop site/field asynchronous freezing.", "no", "no", "SUMMARY_ONLY"),
    rec("I1-12", "Cell-Atom Fusion P0", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_cell_atom_fusion", "experiment/cell-atom-fusion-p0", BASE, "experiments/cell_atom_fusion_p0", "SUMMARY_ONLY", "FAIL", "research_archive/innovation1/cell_atom_fusion", "Can learned cell-atom fusion exploit cross-field interactions?", "A small fusion module improves decisions beyond independent fields.", "Added a gated fusion module.", "Smoke/P0 on 16 cases plus gate-use diagnostics.", "The route failed and the fusion was largely unused by its gate.", "Formal32 eligibility was not reached.", "Do not expand the fusion model; retain as a negative result.", "no", "no", "SUMMARY_ONLY"),
    rec("I1-13", "Field-Time Schedule P0", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_field_schedule", "experiment/field-time-schedule-p0", BASE, "experiments/field_time_schedule_p0", "SUMMARY_ONLY", "ABANDONED_BEFORE_EVALUATION", "research_archive/innovation1/field_time_schedule", "Can a field-by-time schedule outperform a global schedule?", "Field-specific timing is sufficiently heterogeneous to justify scheduling.", "Proposed a frozen field-time schedule.", "Pre-generation heterogeneity diagnostic.", "Diagnostic failed and generation was not run.", "The eligibility gate failed.", "Move away from time/field controllers.", "no", "no", "SUMMARY_ONLY"),
    rec("I1-14", "FP-PC P0", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_fppc", "experiment/fp-pc-p0", BASE, "experiments/fp_pc_p0", "SUMMARY_ONLY", "ABANDONED_BEFORE_EVALUATION", "research_archive/innovation1/fp_pc", "Can a force-proxy predictor-corrector improve sampling?", "Proposal-violation signals can safely trigger correction.", "Added diagnostic FP-PC proposal traces and gates.", "Large proposal diagnostic trace and gate report.", "The diagnostic gate failed; outcome comparison was not estimable.", "Intervention was ineligible before a P0 quality comparison.", "Retain only the diagnostic summary and external trace hash.", "no", "no", "SUMMARY_ONLY"),
    rec("I1-15", "Multifield Self-Conditioning P0", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_self_condition", "experiment/multifield-self-conditioning-p0", BASE, "experiments/multifield_self_conditioning_p0", "SUMMARY_ONLY", "FAIL", "research_archive/innovation1/multifield_self_conditioning", "Can multi-field self-conditioning stabilize generation?", "A learned self-conditioning state improves coherence across fields.", "Trained and evaluated a multi-field self-conditioning checkpoint.", "P0 paired outcomes and quality guardrails.", "P0 failed with severe E-hull degradation.", "Quality guardrails failed.", "Do not scale the checkpoint; preserve its hash externally.", "no", "no", "SUMMARY_ONLY"),
    rec("I1-16", "Self-Correcting Search P0", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_self_correcting_search", "experiment/self-correcting-search-p0", BASE, "experiments/self_correcting_search_p0", "SUMMARY_ONLY", "ABANDONED_BEFORE_EVALUATION", "research_archive/innovation1/self_correcting_search", "Can a learned probe identify timesteps that benefit from correction?", "Probe confidence can select reliable correction steps.", "Added a probe-driven search controller.", "Probe reliability audit and small diagnostic checkpoint.", "No reliable timesteps were found and P0 was not run.", "The probe gate failed.", "Avoid search controllers without an observable reliable signal.", "no", "no", "SUMMARY_ONLY"),
    rec("I1-17", "Branch-Compatible Oracle", "innovation1", MAIN, "experiment/raab-sc-p0", BASE, "experiments/reference_preserved_budgeted_cfg/offline_branchable", "FULL_ARCHIVE", "SUPPORTED", "research_archive/innovation1/branch_oracle", "Does fixed-budget branching expose actionable counterfactual headroom?", "Selecting among reference-preserved branches can avoid harmful single-path adaptation.", "Reframed adaptation as matched-compute branch selection.", "Branchable oracle reports and K-wise outcomes.", "Branch-compatible budgeted headroom passed.", "Oracle evidence alone is not deployable.", "Construct reference-preserved candidate branches and a frozen selector.", "core", "yes/core", "FULL"),
    rec("I1-18", "Reference-Preserved Budgeted Branching", "innovation1", MAIN, "experiment/raab-sc-p0", BASE, "experiments/reference_preserved_budgeted_cfg", "FULL_ARCHIVE", "SUPPORTED", "research_archive/innovation1/reference_branching", "Can branching preserve the reference while using the same budget?", "Explicitly keeping the reference branch reduces downside relative to unconstrained adaptation.", "Added fixed-budget candidates including an untouched reference.", "Offline, feature-study and quality-policy results.", "Reference-preserved branching established the safe design principle used by the final method.", "The general principle was established; allocator choice remained open.", "Compare learned allocation with simple Fixed-K2.", "core", "yes/core", "PARTIAL"),
    rec("I1-19", "Phase B Learned Allocator", "innovation1", MAIN, "experiment/raab-sc-p0", BASE, "experiments/reference_preserved_budgeted_cfg/feature_study", "FULL_ARCHIVE", "NOT_SUPPORTED", "research_archive/innovation1/phase_b_allocator", "Does a learned allocator beat fixed branching at matched compute?", "Features can predict the best two branches better than a fixed choice.", "Trained and frozen the Phase B allocator at C=1.0.", "Held-out selections, validation/test results, reconstruction audit and 20k bootstrap.", "Adaptive allocation value was not supported.", "The registered allocator-advantage gate failed.", "Prefer the simpler Fixed-K2 policy.", "core-negative", "yes/core-negative", "FULL"),
    rec("I1-20", "Frozen C1 Confirmation", "innovation1", "/mnt/datasets-livsyn/dxl/mattergen_v1_linear_k2_confirm", "experiment/frozen-linear-k2-confirmation", BASE, "experiments/frozen_linear_k2_confirmation", "FULL_ARCHIVE", "MIXED", "research_archive/innovation1/frozen_confirmation", "On wholly new paired seeds, do Fixed-K2 and Linear-K2 improve over C0?", "Both frozen K2 policies will preserve gains under confirmatory evaluation.", "Ran a strictly frozen confirmatory cohort with new seeds.", "Generation, paired metrics, 20k bootstrap, quality guardrails and compute accounting.", "Fixed-K2 was supported; learned Linear-K2 was NOT_SUPPORTED.", "The learned policy failed its GO threshold; no rescue tuning was allowed.", "Freeze Fixed-K2 as the thesis method.", "core", "yes/core", "PARTIAL"),
    rec("I1-21", "Final Fixed-K2 Method", "innovation1", FINAL, "release/thesis-final-2026", FINAL_COMMIT, "thesis_release/innovation1", "SUMMARY_ONLY", "SUPPORTED", "research_archive/innovation1/fixed_k2_final", "Which simplest policy survives confirmatory evidence?", "Fixed-K2 reference-preserved branching is sufficient and more defensible than learned allocation.", "Selected the fixed policy after the negative learned confirmation.", "Frozen release tables, 20k bootstrap and quality guardrails.", "Fixed-K2 is the final Innovation 1 thesis method; Linear-K2 remains NOT_SUPPORTED.", "Research question reached its frozen thesis endpoint.", "No post-result tuning; thesis reporting only.", "core", "yes/core", "FULL"),

    # Innovation 2.
    rec("I2-00", "Physics-Guidance Route Selection", "innovation2", MAIN, "experiment/raab-sc-p0", BASE, "experiments/innovation2_research_v2", "SUMMARY_ONLY", "ENGINEERING_ONLY", "research_archive/innovation2/route_selection", "Which physics-guided sampling route is both novel and feasible?", "A systematic failure-pattern and literature audit can narrow the candidate space.", "Compared candidate mechanisms before implementation.", "Literature review, failure-pattern analysis and candidate longlist.", "The audit narrowed the route but did not itself validate a method.", "It was a design-stage study.", "Implement only the top bounded force-guidance candidate.", "supporting", "no", "SUMMARY_ONLY"),
    rec("I2-01", "Stage Reliability Study", "innovation2", "/mnt/datasets-livsyn/dxl/mattergen_v1_matersim_guidance", "experiment/mattersim-late-force-guidance-p0", BASE, "experiments/innovation2_finalization", "SUMMARY_ONLY", "SUPPORTED", "research_archive/innovation2/stage_reliability", "At which denoising stages is surrogate force feedback reliable enough to use?", "Late clean estimates are more reliable than strongly noisy states.", "Added stage-wise reliability diagnostics.", "Frozen diagnostic summaries used by the finalization package.", "Evidence supported restricting guidance to reliable late stages.", "Diagnostic purpose was complete.", "Use clean-x0 estimates and late bounded intervention.", "supporting", "yes/summary", "PARTIAL"),
    rec("I2-02", "Clean-x0 Force Evaluation", "innovation2", "/mnt/datasets-livsyn/dxl/mattergen_v1_matersim_guidance", "experiment/mattersim-late-force-guidance-p0", BASE, "experiments/innovation2_finalization", "SUMMARY_ONLY", "SUPPORTED", "research_archive/innovation2/clean_x0", "Should force be evaluated on noisy x_t or the denoised crystal estimate?", "Clean-x0 evaluation reduces surrogate uncertainty.", "Evaluated the denoised structure for force feedback.", "Reliability diagnostics and frozen method definition.", "Clean-x0 was retained as a supported implementation choice, with explicit causal limitations.", "No separate noisy-x_t confirmatory ablation was available.", "Carry the choice into the frozen P0 protocol.", "supporting", "yes/summary", "PARTIAL"),
    rec("I2-03", "Force-Coordinate Mapping", "innovation2", "/mnt/datasets-livsyn/dxl/mattergen_v1_matersim_guidance", "experiment/mattersim-late-force-guidance-p0", BASE, "experiments/innovation2_finalization", "SUMMARY_ONLY", "SUPPORTED", "research_archive/innovation2/force_coordinate_mapping", "How should Cartesian forces map into periodic fractional-coordinate updates?", "A geometry-consistent mapping prevents direction and scale errors.", "Defined and tested the coordinate transformation used by guidance.", "Implementation tests and final method lock.", "The mapping passed engineering and directional checks.", "Engineering question was resolved.", "Use it unchanged in P0/Formal cohorts.", "supporting", "yes/summary", "PARTIAL"),
    rec("I2-04", "Early Closed-Loop Force Guidance", "innovation2", "/mnt/datasets-livsyn/dxl/mattergen_v1_closed_loop_guidance", "experiment/closed-loop-force-guidance-p0", BASE, "experiments/closed_loop_force_guidance_p0", "FULL_ARCHIVE", "FAIL", "research_archive/innovation2/early_force_guidance", "Does a closed-loop force controller improve generation quality?", "Repeated feedback will outperform the frozen F0 reference.", "Added online feedback beyond F0.", "Sixteen-seed P0 with force and quality endpoints.", "F1 provided no gain over F0 and the route failed.", "The preregistered P0 comparison failed.", "Keep the simpler bounded F0 design; do not tune the failed loop.", "supporting", "no", "PARTIAL"),
    rec("I2-05", "RC-NFGD P0", "innovation2", "/mnt/datasets-livsyn/dxl/mattergen_v1_matersim_guidance", "experiment/mattersim-late-force-guidance-p0", BASE, "experiments/mattersim_late_force_guidance_p0", "FULL_ARCHIVE", "SUPPORTED", "research_archive/innovation2/p0", "Can reliable late-stage force guidance improve initial physical plausibility without harming quality?", "A bounded clean-x0 late-stage correction will reduce pre-relaxation force.", "Froze the first RC-NFGD protocol and fresh paired P0 seeds.", "P0 generation, relaxation, paired metrics and decision.", "P0 passed and justified Formal32.", "P0 was an exploratory gate, not a final claim.", "Freeze the method and run Formal32.", "core", "yes/core", "PARTIAL"),
    rec("I2-06", "RC-NFGD Formal32", "innovation2", "/mnt/datasets-livsyn/dxl/mattergen_v1_matersim_guidance", "experiment/mattersim-late-force-guidance-p0", BASE, "experiments/mattersim_late_force_guidance_formal32", "FULL_ARCHIVE", "SUPPORTED", "research_archive/innovation2/formal32", "Does the P0 effect reproduce on new paired seeds?", "The frozen effect will reproduce at n=32.", "Ran an independent Formal32 with no retuning.", "Decision summary, paired statistics, quality and seed audit.", "The signal reproduced and advanced to Formal256.", "Confirmation scale was still limited.", "Run a wholly new Formal256.", "core", "yes/core", "PARTIAL"),
    rec("I2-07", "RC-NFGD Formal256", "innovation2", "/mnt/datasets-livsyn/dxl/mattergen_v1_matersim_guidance", "experiment/mattersim-late-force-guidance-p0", BASE, "experiments/mattersim_late_force_guidance_formal256", "FULL_ARCHIVE", "SUPPORTED", "research_archive/innovation2/formal256", "Does frozen RC-NFGD provide reproducible matched-seed benefit at formal scale?", "The force and relaxation benefits persist without quality collapse.", "Ran 256 new paired seeds and formal inference.", "Paired statistics, 20k bootstrap, harm/tail analysis and quality guardrails.", "RC-NFGD was supported by the Formal256 evidence.", "Formal endpoint was reached.", "Validate evaluator independence and mechanisms; do not change the method.", "core", "yes/core", "PARTIAL"),
    rec("I2-08", "Independent CHGNet Validation", "innovation2", MAIN, "experiment/raab-sc-p0", BASE, "experiments/final_independent_mlip_validation", "FULL_ARCHIVE", "SUPPORTED", "research_archive/innovation2/chgnet_validation", "Does the force benefit generalize beyond the guiding MatterSim evaluator?", "An independent CHGNet force evaluation will preserve the effect direction.", "Re-evaluated all C0/F0 structures with frozen CHGNet 0.3.0.", "512 structures and two recomputed force endpoints.", "Cross-MLIP generalization was supported, within the stated independence limits.", "The planned independent surrogate check was complete.", "Report as surrogate cross-validation, not DFT.", "core", "yes/core", "FULL"),
    rec("I2-09", "Force-Direction Ablation", "innovation2", "/mnt/datasets-livsyn/dxl/mattergen_v1_matersim_guidance", "experiment/mattersim-late-force-guidance-p0", BASE, "experiments/mattersim_force_direction_ablation", "FULL_ARCHIVE", "SUPPORTED", "research_archive/innovation2/direction_ablation", "Is the physical force direction responsible for benefit rather than matched noise?", "True-force updates outperform random, shuffled and anti-force controls.", "Added magnitude/timing-matched direction controls.", "Five arms, paired metrics and force-direction audit.", "Force-direction effect was supported for the registered comparisons.", "Mechanism question reached its planned endpoint.", "Retain the directional interpretation with surrogate caveats.", "core", "yes/core", "PARTIAL"),
    rec("I2-10", "Trust-Region Ablation", "innovation2", "/mnt/datasets-livsyn/dxl/mattergen_v1_matersim_guidance", "experiment/mattersim-late-force-guidance-p0", BASE, "experiments/mattersim_trust_region_ablation", "FULL_ARCHIVE", "NOT_SUPPORTED", "research_archive/innovation2/trust_region_ablation", "Is the explicit trust region the core source of RC-NFGD benefit?", "A trust-region rule is necessary for the positive effect.", "Isolated the trust-region component.", "Registered ablation results and paired summaries.", "The trust-region mechanism was not supported as the core explanation.", "The isolated component did not meet its evidence rule.", "Keep the empirical frozen method but narrow the mechanism claim.", "supporting", "yes/key-negative", "PARTIAL"),
    rec("I2-11", "Equal-Budget Post-Generation Comparison", "innovation2", "/mnt/datasets-livsyn/dxl/mattergen_v1_matersim_guidance", "experiment/mattersim-late-force-guidance-p0", BASE, "experiments/mattersim_equal_budget_post_generation", "FULL_ARCHIVE", "SUPPORTED", "research_archive/innovation2/equal_budget_post", "Does during-sampling guidance retain value against equal-budget post-processing?", "Online RC-NFGD differs from a compute-matched endpoint corrector.", "Added a post-generation equal-budget comparator.", "Matched-budget results and final comparative audit.", "The registered comparison supported retaining the RC-NFGD interpretation.", "Comparator question was resolved.", "Use the frozen online method in the thesis.", "core", "yes/core", "PARTIAL"),
    rec("I2-12", "Adaptive-CFG Compatibility", "innovation2", "/mnt/datasets-livsyn/dxl/mattergen_v1_matersim_guidance", "experiment/mattersim-late-force-guidance-p0", BASE, "experiments/adaptive_cfg_force_guidance_compatibility", "FULL_ARCHIVE", "FAIL", "research_archive/innovation2/compatibility", "Can Adaptive CFG and F0 retain both benefits when combined?", "The two innovations are compatible under a frozen combined protocol.", "Combined the frozen adaptive-CFG and force-guidance paths.", "Compatibility cohort, dual-benefit retention rule and audit.", "Compatibility failed the frozen retention requirement.", "The combined arm failed; this does not negate RC-NFGD alone.", "Present the innovations separately.", "supporting", "yes/key-negative", "PARTIAL"),
    rec("I2-13", "Bounded-Correction Ablation", "innovation2", MAIN, "experiment/raab-sc-p0", BASE, "experiments/final_bounded_correction_audit", "FULL_ARCHIVE", "NOT_SUPPORTED", "research_archive/innovation2/bounded_correction", "Is norm bounding the necessary mechanism behind the force-guidance benefit?", "Bounded correction outperforms an otherwise matched unbounded update.", "Removed norm-dependent saturation and hard caps while retaining other safeguards.", "Registered three-arm audit.", "Bounding was not supported as the core mechanism.", "The unbounded comparator was not worse under the registered test.", "Narrow the thesis claim to reliable constrained guidance, not bounding necessity.", "supporting", "yes/key-negative", "FULL"),
    rec("I2-14", "E3G Baseline Audit", "innovation2", MAIN, "experiment/raab-sc-p0", BASE, "experiments/final_e3g_baseline_audit", "SUMMARY_ONLY", "INCONCLUSIVE", "research_archive/innovation2/e3g_baseline_audit", "Does an alternative post-generation refiner change the RC-NFGD comparison?", "A strong post-generation reference may explain the apparent benefit.", "Audited the available E3G reference evidence.", "Small audit tables and provenance.", "Evidence was useful context but did not replace the frozen primary comparison.", "It was not a new confirmatory RC-NFGD trial.", "Keep as contextual baseline evidence.", "supporting", "yes/summary", "SUMMARY_ONLY"),
    rec("I2-15", "DFT Environment Verification", "innovation2", MAIN, "experiment/raab-sc-p0", BASE, "experiments/dft_verification", "SUMMARY_ONLY", "ABANDONED_BEFORE_EVALUATION", "research_archive/innovation2/dft_verification", "Can the final claims be verified with DFT in the current environment?", "A suitable DFT runtime and dependencies are available.", "Audited the environment without fabricating DFT results.", "Environment audit JSON and Markdown.", "DFT verification was not run because the required environment was unavailable.", "Environment unavailable; no DFT calculation was authorized or possible.", "Report DFT_VERIFIED=false and treat all physical metrics as surrogate evidence.", "core-limit", "yes/core-limit", "SUMMARY_ONLY"),
    rec("I2-16", "Final RC-NFGD Interpretation", "innovation2", FINAL, "release/thesis-final-2026", FINAL_COMMIT, "thesis_release/innovation2", "SUMMARY_ONLY", "SUPPORTED", "research_archive/innovation2/final_rc_nfgd", "What claim survives all confirmations and ablations?", "RC-NFGD reduces surrogate force/relaxation burden without the tested quality collapse.", "Integrated P0, Formal32, Formal256, CHGNet and ablations.", "Frozen final release tables, report and claim-evidence matrix.", "Innovation 2 is SUPPORTED; DFT_VERIFIED remains false.", "The thesis endpoint was frozen.", "Paper/thesis reporting only; no post-result tuning.", "core", "yes/core", "FULL"),

    # Inherited, already tracked experiments: link rather than duplicate.
    rec("O-01", "Corrector Residual Distillation V1", "other", FINAL, "experiment/corrector-residual-distillation-v1", "d2736e0", "experiments/corrector_residual_distillation_v1", "SUMMARY_ONLY", "MIXED", "research_archive/other_explorations/corrector_distillation/v1", "Can learned residual reuse reduce corrector calls?", "Fallback-gated reuse offers a usable speed-quality trade-off.", "Introduced reuse/adapter/fallback variants.", "Tracked Stage-C screen and audit.", "A promising small candidate appeared but was not a formal success.", "Evidence was exploratory and later routes were stronger.", "Use stricter independent validation.", "no", "no", "SUMMARY_ONLY"),
    rec("O-02", "Corrector Residual Distillation V2", "other", FINAL, "experiment/corrector-residual-distillation-v2", "1b8b622", "experiments/corrector_residual_distillation_v2", "SUMMARY_ONLY", "NOT_SUPPORTED", "research_archive/other_explorations/corrector_distillation/v2", "Does a refined adapter preserve quality while saving forwards?", "Improved training/alignment will repair V1 trade-offs.", "Refined adapter and exact fallback controls.", "Independent evaluation and tests.", "The speed-quality hypothesis was not supported.", "Stopping criteria ruled out further adapter stacking.", "Move to another second-innovation direction.", "no", "no", "SUMMARY_ONLY"),
    rec("O-03", "Corrector Residual Distillation V3 Anchor", "other", FINAL, "experiment/corrector-residual-distillation-v3-anchor", "f983e12", "experiments/corrector_residual_distillation_v3_anchor", "SUMMARY_ONLY", "FAIL", "research_archive/other_explorations/corrector_distillation/v3_anchor", "Can anchoring repair residual reuse tails?", "An anchored adapter prevents V2 geometry/force tails.", "Added teacher anchoring and frozen independent64.", "Independent64 and tail validation.", "The registered Stage-C criteria failed.", "Tail robustness was not confirmed.", "Stop the family without retuning K/thresholds.", "no", "no", "SUMMARY_ONLY"),
    rec("O-04", "Corrector Distillation Formal256", "other", FINAL, "experiment/corrector-residual-distillation-formal256", "0a1a8e2", "experiments/corrector_residual_distillation_formal256", "SUMMARY_ONLY", "INCONCLUSIVE", "research_archive/other_explorations/corrector_distillation/formal256", "Is the corrector method non-inferior on formal quality and force tails?", "Speed gains preserve all registered safety margins.", "Ran formal256 with frozen margins.", "Formal report and paired intervals.", "Neither PASS nor FAIL was established because force-tail intervals were too wide.", "Registered non-inferiority remained unresolved.", "Do not call it quality-equivalent.", "no", "no", "SUMMARY_ONLY"),
    rec("O-05", "Cross-Field Interaction P0", "other", FINAL, "experiment/cross-field-interaction-p0", "7bc2282", "experiments/cross_field_interaction_p0", "SUMMARY_ONLY", "INCONCLUSIVE", "research_archive/other_explorations/cross_field_interaction/p0", "Do cross-field interactions beat a matched MLP?", "Explicit interaction modeling improves multiple endpoints.", "Added CFI and matched MLP arms.", "Eight-seed P0.", "A cautious GO signal appeared with a relaxation-tail outlier.", "n=8 could not support confirmation.", "Freeze and test on P1.", "no", "no", "SUMMARY_ONLY"),
    rec("O-06", "Cross-Field Interaction P1", "other", FINAL, "experiment/cross-field-interaction-p1", "70a85b7", "experiments/cross_field_interaction_p1", "SUMMARY_ONLY", "FAIL", "research_archive/other_explorations/cross_field_interaction/p1", "Does the CFI P0 benefit reproduce?", "The core quality signal persists on 32 seeds.", "Ran frozen P1.", "P1 paired endpoints and tails.", "Core signal did not reproduce and novelty degraded.", "The preregistered P1 gate failed.", "Stop CFI and do not launch P2.", "no", "no", "SUMMARY_ONLY"),
    rec("O-07", "Distribution-Constrained Quality Adapter P0", "other", FINAL, "experiment/distribution-constrained-quality-adapter-p0", "399488b", "experiments/distribution_constrained_quality_adapter_p0", "SUMMARY_ONLY", "INCONCLUSIVE", "research_archive/other_explorations/distribution_adapter/p0", "Can quality weighting improve conditioned generation?", "A static M2 adapter improves quality without collapse.", "Added quality-weighted adapter training.", "Eight-seed P0.", "Positive exploratory signal justified P1.", "Small sample was not confirmatory.", "Freeze M2 and run P1.", "no", "no", "SUMMARY_ONLY"),
    rec("O-08", "Distribution-Constrained Quality Adapter P1", "other", FINAL, "experiment/distribution-constrained-quality-adapter-p1", "180acb6", "experiments/distribution_constrained_quality_adapter_p1", "SUMMARY_ONLY", "MIXED", "research_archive/other_explorations/distribution_adapter/p1", "Does M2 preserve quality gain without distribution contraction?", "P0 quality gains reproduce while novelty/composition remain safe.", "Ran 32-seed independent validation.", "Quality, force and distribution paired metrics.", "Quality/force signals coexisted with novelty/composition trade-offs; BORDERLINE historically.", "Neither GO nor FAIL criteria were met.", "Test one restricted weight-contrast change.", "no", "no", "SUMMARY_ONLY"),
    rec("O-09", "Distribution Adapter P1b", "other", FINAL, "experiment/distribution-constrained-quality-adapter-p1b", "71f4619", "experiments/distribution_constrained_quality_adapter_p1b", "SUMMARY_ONLY", "FAIL", "research_archive/other_explorations/distribution_adapter/p1b", "Can lower weight contrast restore distribution coverage?", "A restricted contrast change creates a quality-distribution Pareto point.", "Tested exactly two lower contrasts.", "Sixteen-seed screen.", "Neither candidate achieved the registered Pareto criterion.", "Both candidates triggered stopping rules.", "Stop weight tuning and do not run P2.", "no", "no", "SUMMARY_ONLY"),
    rec("O-10", "Distribution-Balanced Quality Adapter", "other", FINAL, "experiment/distribution-balanced-quality-adapter", "d8f8014", "experiments/distribution_balanced_quality_adapter", "SUMMARY_ONLY", "FAIL", "research_archive/other_explorations/distribution_adapter/balanced", "Can explicit distribution balancing recover the adapter trade-off?", "Balancing restores coverage while retaining quality gains.", "Added distribution-balanced weighting.", "Sixteen-seed decision experiment.", "The GO rule failed and no 32-seed confirmation was run.", "Registered decision was FAIL.", "Stop the route.", "no", "no", "SUMMARY_ONLY"),
    rec("O-11", "Global Transformer Adapter P0", "other", FINAL, "experiment/global-transformer-adapter-p0", "499dba7", "experiments/global_transformer_adapter_p0", "SUMMARY_ONLY", "FAIL", "research_archive/other_explorations/global_transformer", "Can global interactions improve on generic PEFT?", "A Transformer adapter gives stable cross-field gains.", "Added a global Transformer adapter and matched controls.", "Eight-seed P0.", "Geometry/relaxation regression triggered FAIL.", "Predeclared failure condition was met.", "Do not freeze for P1.", "no", "no", "SUMMARY_ONLY"),
    rec("O-12", "TCL and DML P0", "other", FINAL, "experiment/tcl-dml-p0", "2f95aa0", "experiments/tcl_dml_p0", "SUMMARY_ONLY", "MIXED", "research_archive/other_explorations/tcl/dml_p0", "Which training intervention merits validation?", "TCL and DML repair the base fine-tuning failure.", "Compared TCL and DML.", "P0 decision report.", "TCL received GO; DML failed.", "Only TCL qualified.", "Advance frozen TCL only.", "no", "no", "SUMMARY_ONLY"),
    rec("O-13", "TCL P1", "other", FINAL, "experiment/tcl-p1", "56efbaa", "experiments/tcl_p1", "SUMMARY_ONLY", "SUPPORTED", "research_archive/other_explorations/tcl/p1", "Does TCL repair FT0 degradation?", "TCL improves over FT0 on new seeds.", "Ran frozen P1.", "P1 paired report.", "P1 achieved CLEAR GO under its historical criteria.", "Required larger replication.", "Run P2.", "no", "no", "SUMMARY_ONLY"),
    rec("O-14", "TCL P2", "other", FINAL, "experiment/tcl-p2", "b9fd990", "experiments/tcl_p2", "SUMMARY_ONLY", "SUPPORTED", "research_archive/other_explorations/tcl/p2", "Does TCL reproduce at n=64?", "TCL-over-FT0 benefits persist.", "Ran frozen P2.", "P2 inference and guardrails.", "Historical CLEAR GO versus FT0 reproduced.", "Comparison against C0 remained unresolved.", "Run formal comparison including C0.", "no", "no", "SUMMARY_ONLY"),
    rec("O-15", "TCL Formal256", "other", FINAL, "experiment/tcl-formal256", "6ed463c", "experiments/tcl_formal256", "SUMMARY_ONLY", "FAIL", "research_archive/other_explorations/tcl/formal256", "Does TCL beat FT0 while remaining safe relative to C0?", "TCL's FT0 gains satisfy the complete formal rule.", "Ran frozen Formal256 with C0 safeguards.", "Formal paired tests and Holm inference.", "TCL beat FT0, but final registered rules failed due to C0 geometry/force protection.", "The overall formal decision was FAIL.", "Do not select TCL as the final innovation.", "no", "no", "SUMMARY_ONLY"),
    rec("O-16", "TCL Formal Root-Cause Analysis", "other", FINAL, "analysis/tcl-formal256-root-cause", "eaf2692", "experiments/tcl_formal256_root_cause", "SUMMARY_ONLY", "SUPPORTED", "research_archive/other_explorations/tcl/root_cause", "What caused TCL's formal geometry degradation?", "Late position drift and shared-field coupling explain the tail.", "Performed saved-state drift, gradient, composition and structure analyses.", "Root-cause report and diagnostic tables.", "Late position drift and objective/field coupling were supported; sampling amplification remained only moderate/plausible.", "Diagnostic aim was complete.", "Motivated anchored/field-safe variants, without changing Formal FAIL.", "no", "no", "SUMMARY_ONLY"),
    rec("O-17", "GBSA-TCL P0", "other", FINAL, "experiment/gbsa-tcl-p0", "5a72cfd", "experiments/gbsa_tcl_p0", "SUMMARY_ONLY", "INCONCLUSIVE", "research_archive/other_explorations/gbsa/p0", "Can score anchoring and partial freezing repair TCL?", "GBSA restores geometry without quality collapse.", "Added score anchoring and partial freezing.", "Eight-seed directional P0.", "Historical P0 GO justified P1 but was not confirmatory.", "n=8 was insufficient.", "Freeze and run P1.", "no", "no", "SUMMARY_ONLY"),
    rec("O-18", "GBSA-TCL P1", "other", FINAL, "experiment/gbsa-tcl-p1", "b129851", "experiments/gbsa_tcl_p1", "SUMMARY_ONLY", "FAIL", "research_archive/other_explorations/gbsa/p1", "Does GBSA repair force robustness on new seeds?", "P0 benefits reproduce without force tails.", "Ran frozen P1.", "P1 paired metrics and outlier audit.", "A severe force outlier broke the force-robustness gate.", "Registered P1 decision was FAIL.", "Stop before P2; consider a distinct atomic-only hypothesis.", "no", "no", "SUMMARY_ONLY"),
    rec("O-19", "Frozen GBSA Prospective32", "other", FINAL, "experiment/gbsa-tcl-prospective32", BASE, "experiments/gbsa_tcl_prospective32", "SUMMARY_ONLY", "FAIL", "research_archive/other_explorations/gbsa/prospective32", "Does prospective freezing change the GBSA conclusion?", "A new frozen cohort confirms NUS and safety.", "Ran new 32 paired seeds under a primary/guardrail framework.", "20k bootstrap, endpoints and tail sensitivity.", "NUS uncertainty and safety non-inferiority failed the rule.", "Prospective verdict was FAIL.", "Stop GBSA and do not run independent64.", "no", "no", "SUMMARY_ONLY"),
    rec("O-20", "Metric Framework Reassessment", "other", FINAL, "release/thesis-final-2026", FINAL_COMMIT, "experiments/metric_framework_reassessment", "SUMMARY_ONLY", "ENGINEERING_ONLY", "research_archive/other_explorations/metric_reassessment", "How should heterogeneous historical experiments be compared without relabeling them?", "A common primary/guardrail framework clarifies evidence.", "Performed retrospective tabulation only.", "Historical table and resampling analyses.", "The reassessment organized evidence but did not change historical verdicts.", "No new method was executed.", "Use the framework prospectively.", "supporting", "yes/summary", "SUMMARY_ONLY"),

    # Remote-only research branches found during the all-ref inventory.
    rec("R-01", "A0-E3G Independent64", "other", "remote-only", "origin/feature/a0-e3g-independent64", "3bafb64", "git:reports/a0_e3g_independent64", "SUMMARY_ONLY", "SUPPORTED", "research_archive/other_explorations/remote_branch_studies/a0_e3g_independent64", "Does E3G improve force on an independent64 cohort?", "The frozen refiner effect reproduces.", "Ran an independent64 refiner evaluation.", "Remote branch final report and summary.", "Historical independent64 state was GO.", "Required formal validation.", "Proceed to formal256 without reusing training seeds.", "no", "no", "SUMMARY_ONLY"),
    rec("R-02", "A0-E3G Compatibility64", "other", "remote-only", "origin/feature/a0-e3g-compatibility64", "447fa7e", "git:reports/a0_e3g_compat64", "SUMMARY_ONLY", "SUPPORTED", "research_archive/other_explorations/remote_branch_studies/a0_e3g_compatibility64", "Is E3G compatible with A0?", "The combined path retains its frozen gates.", "Ran a 64-case compatibility study.", "Remote final report.", "Historical final state was GO.", "Compatibility stage completed.", "Treat separately from later MatterGen force guidance.", "no", "no", "SUMMARY_ONLY"),
    rec("R-03", "A0-E3G Formal256 Eligibility", "other", "remote-only", "origin/feature/a0-e3g-formal256", "33f8a69", "git:reports/a0_e3g_formal256", "SUMMARY_ONLY", "INCONCLUSIVE", "research_archive/other_explorations/remote_branch_studies/a0_e3g_formal256", "Was the available Formal256 source cohort eligible?", "Existing A0 data can support an independent formal claim.", "Audited training-seed overlap before reuse.", "Formal reuse audit and final summary.", "SOURCE_DATA_INCOMPLETE/formally ineligible because 64 seeds overlapped training.", "A wholly new authorized cohort was required.", "Do not mix partial old and new cohorts.", "no", "no", "SUMMARY_ONLY"),
    rec("R-04", "A0-E3G Leakage Diagnostic256", "other", "remote-only", "origin/experiment/a0-e3g-leakage-diagnostic256", "4efe6d5", "git:reports/a0_e3g_leakage256", "SUMMARY_ONLY", "MIXED", "research_archive/other_explorations/remote_branch_studies/a0_e3g_leakage256", "Did training overlap distort the E3G result?", "Held-out and overlap cohorts should show consistent gate behavior.", "Separated training-overlap and held-out cohorts.", "Leakage diagnostic and cohort metrics.", "Held-out benefits coexisted with materially different harmful-decision counts across cohorts.", "Diagnostic could not convert the ineligible formal cohort into a confirmation.", "Preserve as a leakage warning.", "no", "no", "SUMMARY_ONLY"),
    rec("R-05", "Budget-Aware Corrector Gating", "other", "remote-only", "origin/feature/budget-aware-corrector-gating", "7561f4e", "git:research/budget_aware_gating", "SUMMARY_ONLY", "NOT_SUPPORTED", "research_archive/other_explorations/remote_branch_studies/budget_aware_gating", "Can budget-aware gates yield useful speed-quality trade-offs?", "Frozen gates save forwards while preserving quality.", "Added two budget-aware policies.", "32-seed development screen.", "Both policies were historical NO_GO.", "Quality/speed gates did not jointly pass.", "Do not start the registered confirmatory cohort.", "no", "no", "SUMMARY_ONLY"),
    rec("R-06", "Convergence-Aware Corrector Gating", "other", "remote-only", "origin/feature/convergence-aware-corrector-gating", "9feb77f", "git:mattergen/diffusion/sampling/corrector_gating.py", "SUMMARY_ONLY", "ENGINEERING_ONLY", "research_archive/other_explorations/remote_branch_studies/convergence_aware_gating", "Can convergence signals skip corrector work safely?", "Convergence-aware gating produces real throughput gains.", "Added convergence-aware execution gates.", "The remote branch contains implementation and tests, but no archived scientific decision report was found.", "The implementation exists; no scientific performance verdict can be reconstructed from that branch alone.", "No confirmatory decision artifact was available.", "Retain branch provenance only.", "no", "no", "SUMMARY_ONLY"),
    rec("R-07", "CG-TDR", "other", "remote-only", "origin/feature/cg-tdr", "cb67f1e", "git:research/cg_tdr", "SUMMARY_ONLY", "NOT_SUPPORTED", "research_archive/other_explorations/remote_branch_studies/cg_tdr", "Can learned time-dependent residuals repair correction?", "A residual model generalizes to held-out sampling.", "Trained V1/V2 residual predictors.", "Remote training/evaluation decisions.", "Residual generalization was too weak for a useful effect.", "The route was historical No-Go.", "Do not expand the residual model.", "no", "no", "SUMMARY_ONLY"),
    rec("R-08", "CrystalREPA Reproduction", "other", "remote-only", "origin/feature/crystalrepa-repro", "5411a7d", "git:research/crystalrepa_repro", "SUMMARY_ONLY", "NOT_SUPPORTED", "research_archive/other_explorations/remote_branch_studies/crystalrepa", "Does a CrystalREPA-style method reproduce under this setup?", "The reproduced representation method improves matched baselines.", "Implemented a constrained reproduction.", "Training and 64-case evaluation summaries.", "Engineering and scientific GO were both false.", "Registered reproduction decision was NO_GO.", "Retain limitations and do not claim a reproduction success.", "no", "no", "SUMMARY_ONLY"),
    rec("R-09", "FN-PRA", "other", "remote-only", "origin/feature/fn-pra", "a620523", "git:research/fn_pra", "SUMMARY_ONLY", "NOT_SUPPORTED", "research_archive/other_explorations/remote_branch_studies/fn_pra", "Can force-normalized post-refinement improve quality and geometry?", "The module creates a robust Pareto gain.", "Added FN-PRA and a frozen phase-1 screen.", "32-case report and decision.", "Trade-off signals existed, but engineering/scientific gates were NO_GO.", "Composition/replication requirements were not met.", "Do not promote to thesis method.", "no", "no", "SUMMARY_ONLY"),
    rec("R-10", "GemNet Fused Inference Fastgate", "other", "remote-only", "origin/feature/gemnet-fused-inference-fastgate", "83b468f", "git:research/gemnet_fused_fastgate", "SUMMARY_ONLY", "ENGINEERING_ONLY", "research_archive/other_explorations/remote_branch_studies/gemnet_fused", "Can kernel fusion accelerate the guidance path?", "Fused inference meets equivalence and speed gates.", "Prototyped fused GemNet operations.", "Microbenchmarks and numerical checks.", "GPU acceleration was NO_GO; strict equivalence and throughput gates failed.", "Generation was not started after engineering gates failed.", "Keep as an engineering negative result.", "no", "no", "SUMMARY_ONLY"),
    rec("R-11", "MPS Runtime Fastgate", "other", "remote-only", "origin/feature/mps-runtime-fastgate", "e2aef29", "git:research/mps_fastgate", "SUMMARY_ONLY", "ENGINEERING_ONLY", "research_archive/other_explorations/remote_branch_studies/mps_runtime", "Can an MPS-style runtime optimization help MatterGen?", "The runtime path passes a fast engineering gate.", "Implemented a runtime prototype.", "Remote benchmark report.", "Final state was MPS_NO_GO.", "Engineering performance gate failed.", "Do not spend quality-evaluation budget.", "no", "no", "SUMMARY_ONLY"),
    rec("R-12", "Post-Generation Quality Modules Fastgate", "other", "remote-only", "origin/feature/postgen-quality-modules-fastgate", "9aa23f9", "git:reports/postgen_fastgate", "SUMMARY_ONLY", "MIXED", "research_archive/other_explorations/remote_branch_studies/postgen_modules", "Which post-generation quality module merits validation?", "At least one small refiner offers safe force reduction.", "Screened several post-generation modules.", "Fastgate reports and Q3 summary.", "Most candidates were NO_GO; Q3 E3-PCR advanced.", "Only one candidate justified confirmation.", "Validate frozen Q3 on independent seeds.", "no", "no", "SUMMARY_ONLY"),
    rec("R-13", "Q3 E3-PCR Frozen64", "other", "remote-only", "origin/feature/q3-e3-pcr-frozen64", "87853b0", "git:reports/q3_e3_pcr/frozen64", "SUMMARY_ONLY", "MIXED", "research_archive/other_explorations/remote_branch_studies/q3_e3_pcr_frozen64", "Does Q3 reproduce and is the learned gate necessary?", "The refiner and learned gate both outperform controls.", "Ran frozen64 with always-on/random controls.", "Remote final report and ablation.", "Force benefit reproduced, but the learned-gate mechanism was not supported at this stage.", "Formal confirmation was still required.", "Run frozen Formal256 and report mechanism separately.", "no", "no", "SUMMARY_ONLY"),
    rec("R-14", "Q3 E3-PCR Formal256", "other", "remote-only", "origin/feature/q3-e3-pcr-formal256", "d91598b", "git:reports/q3_e3_pcr/formal256", "SUMMARY_ONLY", "SUPPORTED", "research_archive/other_explorations/remote_branch_studies/q3_e3_pcr_formal256", "Does Q3 E3-PCR confirm at 256 seeds?", "The frozen learned-gated refiner passes primary and quality gates.", "Ran a wholly new Formal256.", "Remote final summary and paired metrics.", "Historical final state was E3_G_FORMAL_CONFIRMED; DFT remained false.", "The formal endpoint was reached.", "Preserve as a separate historical route, not the current thesis Innovation 2.", "no", "no", "SUMMARY_ONLY"),
    rec("R-15", "RP-QTFG", "other", "remote-only", "origin/feature/rp-qtfg", "f413e4c", "git:research/rp_qtfg", "SUMMARY_ONLY", "NOT_SUPPORTED", "research_archive/other_explorations/remote_branch_studies/rp_qtfg", "Can online query-time force guidance improve structures?", "Matched online physics updates improve at least one primary endpoint safely.", "Implemented an online CHGNet-guided MVP.", "Eight-seed Gate 1 and controls.", "The MVP was NO_GO and the 32-seed stage was not started.", "All candidates worsened RMSD or other guardrails.", "Stop the online MVP.", "no", "no", "SUMMARY_ONLY"),
    rec("R-16", "SPG MatterGen Fastgate", "other", "remote-only", "origin/feature/spg-mattergen-fastgate", "a6718d2", "git:research/spg_fastgate", "SUMMARY_ONLY", "MIXED", "research_archive/other_explorations/remote_branch_studies/spg_fastgate", "Can static periodic-graph execution accelerate MatterGen safely?", "Static graph handling enables faster generation.", "Added SPG prototypes and quality checks.", "Fastgate report.", "The overall fastgate advanced, while native batching and field-safe BF16 did not.", "Subcomponents failed and required an MVP study.", "Evaluate a narrowly scoped static-graph MVP.", "no", "no", "SUMMARY_ONLY"),
    rec("R-17", "SPG Static Periodic Graph MVP", "other", "remote-only", "origin/feature/spg-static-periodic-graph-mvp", "425bfdc", "git:research/spg_static_mvp", "SUMMARY_ONLY", "ENGINEERING_ONLY", "research_archive/other_explorations/remote_branch_studies/spg_static_mvp", "Does a single-bucket static graph meet performance gates?", "Static execution preserves correctness and improves throughput.", "Built a single-bucket MVP.", "Correctness and performance benchmarks.", "Correctness passed but performance gates failed; generation was not run.", "Final state was SINGLE_BUCKET_NO_GO.", "Do not generalize from the failed MVP.", "no", "no", "SUMMARY_ONLY"),

    # Loose server artifacts with no complete experiment package.
    rec("X-01", "ALM-GEN P0 Residual Structures", "other", MAIN, "experiment/alm-gen-p0", BASE, "experiments/alm_gen_p0", "EXTERNAL_DATA_ONLY", "INCONCLUSIVE", "research_archive/other_explorations/alm_gen_p0", "Was ALM-GEN evaluated as a viable route?", "Generated structures would support a P0 decision.", "Only residual structure artifacts were found.", "Two structure subtrees; no recoverable decision report or implementation package in the MatterGen worktrees.", "No defensible scientific verdict can be reconstructed.", "Evidence package is incomplete.", "Keep hashes and request manual review before deletion.", "no", "no", "EXTERNAL_ONLY", "MANUAL_REVIEW_REQUIRED"),
    rec("X-02", "Composable Property Adapter Residual Artifacts", "other", MAIN, "experiment/composable-property-adapter-p0", BASE, "experiments/composable_property_adapter_p0", "EXTERNAL_DATA_ONLY", "INCONCLUSIVE", "research_archive/other_explorations/composable_property_adapter", "Did composable adapters improve property control?", "Small adapters compose without quality loss.", "Two adapter weights and a 12-generation smoke run remain.", "Ignored weights and logs; no final report/source package was found here.", "The surviving evidence is insufficient for a scientific verdict.", "Decision artifacts are missing.", "Retain external hashes and mark for manual review.", "no", "no", "EXTERNAL_ONLY", "MANUAL_REVIEW_REQUIRED"),
    rec("X-03", "MatterGen LoRA Residual Artifacts", "other", MAIN, "experiment/mattergen-lora-p0", BASE, "experiments/mattergen_lora_p0", "EXTERNAL_DATA_ONLY", "INCONCLUSIVE", "research_archive/other_explorations/mattergen_lora", "Did LoRA provide a useful property-control route?", "LoRA matches official tuning with fewer trainable parameters.", "Ran a four-seed smoke comparison.", "Generation logs and bytecode caches only; no final decision package was found.", "No recoverable confirmatory conclusion.", "Source and report were not present in the scanned worktrees.", "Keep a manifest, not bytecode/log bulk.", "no", "no", "EXTERNAL_ONLY", "MANUAL_REVIEW_REQUIRED"),
    rec("X-04", "MatterGen RL P0", "other", MAIN, "experiment/mattergen-rl-p0", BASE, "experiments/mattergen_rl_p0", "SUMMARY_ONLY", "INCONCLUSIVE", "research_archive/other_explorations/mattergen_rl", "Can reward-weighted denoising improve magnetic-density targeting?", "A surrogate-reward loop increases target reward without collapse.", "Ran smoke and ten-iteration formal optimization.", "Completion log reports reward rise but no archived paired held-out final decision.", "The training run completed, but the remaining evidence is not a confirmatory method result.", "No final report/source package survived in the scanned worktree.", "Manual review before any scientific reuse.", "no", "no", "SUMMARY_ONLY", "MANUAL_REVIEW_REQUIRED"),
    rec("X-05", "Final Thesis Results Build Package", "other", MAIN, "experiment/raab-sc-p0", BASE, "experiments/final_thesis_results", "IGNORE", "ENGINEERING_ONLY", "research_archive/ignored/final_thesis_results_duplicate", "Should the generated final package be copied again?", "A second copy would improve preservation.", "Compared it against the frozen thesis release.", "The final release already contains the curated tables, methods, figures and audits.", "This is a duplicate build/output source, not a distinct experiment.", "Duplication would add noise and internal paths.", "Reference release/thesis-final-2026 instead.", "core", "yes/full", "SUMMARY_ONLY"),
]


assert all(row["category"] in ALLOWED_CATEGORIES for row in EXPERIMENTS)
assert all(row["status"] in ALLOWED_STATUSES for row in EXPERIMENTS)
assert len({row["experiment_id"] for row in EXPERIMENTS}) == len(EXPERIMENTS)
assert len({row["archive_target"] for row in EXPERIMENTS}) == len(EXPERIMENTS)
